// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9mgIxSpHwLNEIPYziSNzGmjJG7okzEsk',
    appId: '1:1004518766142:web:345844cb6b29c4cda0c36f',
    messagingSenderId: '1004518766142',
    projectId: 'mymeal-83754',
    authDomain: 'mymeal-83754.firebaseapp.com',
    storageBucket: 'mymeal-83754.firebasestorage.app',
    measurementId: 'G-89JKPXZB1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-MAHZVevotGwpz-OljtRcRzklBjnFg4k',
    appId: '1:1004518766142:android:a3aaf8acab437939a0c36f',
    messagingSenderId: '1004518766142',
    projectId: 'mymeal-83754',
    storageBucket: 'mymeal-83754.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcdDWiqhVbReR-hzpCTaVNGrSthmq14Ko',
    appId: '1:1004518766142:ios:4a2dbfed194ea24ea0c36f',
    messagingSenderId: '1004518766142',
    projectId: 'mymeal-83754',
    storageBucket: 'mymeal-83754.firebasestorage.app',
    iosBundleId: 'com.example.mymeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcdDWiqhVbReR-hzpCTaVNGrSthmq14Ko',
    appId: '1:1004518766142:ios:4a2dbfed194ea24ea0c36f',
    messagingSenderId: '1004518766142',
    projectId: 'mymeal-83754',
    storageBucket: 'mymeal-83754.firebasestorage.app',
    iosBundleId: 'com.example.mymeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9mgIxSpHwLNEIPYziSNzGmjJG7okzEsk',
    appId: '1:1004518766142:web:da7e8038524fe300a0c36f',
    messagingSenderId: '1004518766142',
    projectId: 'mymeal-83754',
    authDomain: 'mymeal-83754.firebaseapp.com',
    storageBucket: 'mymeal-83754.firebasestorage.app',
    measurementId: 'G-JJLSRXM6L2',
  );
}
